---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  # You may wish to disable always updating cookbooks in CI or other testing environments.
  # For example:
  #   always_update_cookbooks: <%= !ENV['CI'] %>
  # always_update_cookbooks: true

  product_name: chef
  product_version: 14

  environments_path: 'test/integration/environments'
  roles_path: 'test/integration/roles'

  client_rb:
    environment: 'test'

verifier:
  name: inspec

platforms:
  - name: centos-7

suites:
  - name: default
    data_bags_path: "test/integration/data_bags"
    encrypted_data_bag_secret_key_path: "test/integration/files/encrypted_data_bag_secret"
    run_list:
      - role[slack_test]
    verifier:
      inspec_tests:
        - test/integration/default
    attributes:
